"""Model loading and prediction helpers.

`RainfallPredictor` 是離線推論與驗證流程的核心類別。它負責依照
設定建立模型、載入 checkpoint、把輸入影像轉成模型輸入，最後把
softmax 輸出轉成每個像素的雨量標籤。
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np

from typhoon_rainfall.config import DataConfig, ModelConfig, PredictConfig
from typhoon_rainfall.data.contracts import DatasetPaths, InputModes, SamplePair, compute_input_shape
from typhoon_rainfall.data.dataset import build_dataset_paths, merge_modal_arrays, merge_modalities
from typhoon_rainfall.inference.checkpoints import resolve_checkpoint
from typhoon_rainfall.models.factory import build_model
from typhoon_rainfall.visualization.plotting import save_prediction_array, save_prediction_plot


@dataclass
class PredictionArtifacts:
    """Files generated by one prediction call."""

    prediction_labels: np.ndarray
    csv_path: Optional[Path] = None
    png_path: Optional[Path] = None


class RainfallPredictor:
    """High-level predictor for validation data or manually provided images."""

    def __init__(
        self,
        data_config: DataConfig,
        model_config: ModelConfig,
        predict_config: PredictConfig,
    ) -> None:
        self.data_config = data_config
        self.model_config = model_config
        self.predict_config = predict_config
        self.dataset_paths = build_dataset_paths(self.data_config)
        self.input_modes = InputModes.from_data_config(self.data_config)
        self.model = self._load_model()

    def _load_model(self):
        """Build the configured model and load its checkpoint weights."""
        input_shape = compute_input_shape(self.data_config.image_size, self.input_modes)
        # The model name comes from configs/default.json or a CLI override.
        # For the default research setup this is usually Unet5.
        model = build_model(
            name=self.model_config.name,
            input_shape=input_shape,
            num_classes=self.model_config.num_classes,
        )
        # If checkpoint_path is None, resolve_checkpoint will first try
        # checkpoint/{model_name}_val_min_RMSE.h5, then fall back to latest .h5.
        checkpoint_path = resolve_checkpoint(
            checkpoint_dir=self.model_config.checkpoint_dir,
            model_name=self.model_config.name,
            explicit_path=self.model_config.checkpoint_path,
        )
        print("\nModel loading")
        print(f"- model: {self.model_config.name}")
        print(f"- input_shape: {input_shape}")
        print(f"- checkpoint: {checkpoint_path}")
        model.load_weights(str(checkpoint_path))
        return model

    def predict_dataset_pair(self, split: str, pair: SamplePair) -> np.ndarray:
        """Predict one pair listed in train/val annotation files."""
        merged = merge_modalities(
            dataset_paths=self.dataset_paths,
            split=split,
            sample_name=pair.source_name,
            input_modes=self.input_modes,
            num_classes=self.model_config.num_classes,
        )
        return self.predict_array(merged)

    def predict_array(self, merged_input: np.ndarray) -> np.ndarray:
        """Run model inference on a pre-merged input array and return labels."""
        prediction = self.model.predict(np.asarray([merged_input]), verbose=0)[0]
        return prediction.argmax(axis=-1).reshape(self.data_config.image_size)

    def predict_modal_images(self, rd_image=None, ir_image=None, ra_image=None) -> np.ndarray:
        """Predict from already-open RD/IR/RA images.

        This is used by PyCharm-friendly single-image scripts and the legacy
        crawler flow. GI images are loaded automatically when GI is enabled.
        """

        lon_image = None
        lat_image = None
        if self.input_modes.use_gi:
            from PIL import Image

            lon_image = Image.open(self.dataset_paths.lon_path())
            lat_image = Image.open(self.dataset_paths.lat_path())
        merged = merge_modal_arrays(
            input_modes=self.input_modes,
            num_classes=self.model_config.num_classes,
            rd_image=rd_image,
            ir_image=ir_image,
            ra_image=ra_image,
            lon_image=lon_image,
            lat_image=lat_image,
        )
        return self.predict_array(merged)

    def save_prediction(self, prediction: np.ndarray, stem: str) -> PredictionArtifacts:
        """Save prediction labels to CSV and a colorized PNG."""
        self.predict_config.prediction_array_dir.mkdir(parents=True, exist_ok=True)
        self.predict_config.prediction_plot_dir.mkdir(parents=True, exist_ok=True)
        csv_path = self.predict_config.prediction_array_dir / f"{stem}.csv"
        png_path = self.predict_config.prediction_plot_dir / f"{stem}.png"
        save_prediction_array(prediction, csv_path)
        save_prediction_plot(prediction, png_path)
        return PredictionArtifacts(prediction_labels=prediction, csv_path=csv_path, png_path=png_path)
